version: '3.8'
services:

  app:
    build: ./
    ports:
      - 80:80
    working_dir: /
    image: eurohard_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: eurohard
      MYSQL_ROOT_PASSWORD: eurohard
      MYSQL_PASSWORD: eurohard
      MYSQL_USER: eurohard
    volumes:
      - ./database_local:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: db
      PMA_USER: eurohard
      PMA_PASSWORD: eurohard
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
